### ISSUE TITLE
Устанавливать таймаут в конфиге

### ISSUE THREAD

**Issue by anaumov** [actie/fnsapi#6]
https://github.com/actie/fnsapi/blob/4dd37d2538bb4728b89e58aa9ffa497c498eab52/lib/fnsapi/kkt_service.rb#L34

захардкожен таймаунт, надо вынести в настройки. Ответ ФНС до минуты может идти.

**Comment by fedorkk** [comment]
https://github.com/actie/fnsapi/pull/7
